# Generated by Django 5.0.10 on 2025-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstsectiongroupings',
            name='design_options',
            field=models.ManyToManyField(blank=True, db_column='DESIGN_OPTIONS', null=True, to='masters.mstdesignoptions'),
        ),
        migrations.AlterField(
            model_name='mstsectiongroupings',
            name='rules',
            field=models.ManyToManyField(blank=True, db_column='RULES', null=True, to='masters.mstsectionrules'),
        ),
        migrations.AlterUniqueTogether(
            name='mstsectionrules',
            unique_together={('design_doc', 'rule_number')},
        ),
    ]
