# Generated by Django 5.0.10 on 2025-01-17 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_mstsectiongroupings_design_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcategory',
            name='is_verifier',
            field=models.BooleanField(db_column='IS_VERIFIER', default=True),
        ),
        migrations.AddField(
            model_name='mstsubcategory',
            name='is_verifier',
            field=models.BooleanField(db_column='IS_VERIFIER', default=True),
        ),
        migrations.AlterField(
            model_name='mstsectiongroupings',
            name='design_options',
            field=models.ManyToManyField(blank=True, db_column='DESIGN_OPTIONS', null=True, related_name='section_groups', to='masters.mstdesignoptions'),
        ),
        migrations.CreateModel(
            name='MstConditions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('condition_variable', models.CharField(db_column='CONDITION_VARIABLE', max_length=255)),
                ('condition_operator', models.CharField(blank=True, db_column='CONDITION_OPERATOR', max_length=2, null=True)),
                ('condition_min_value', models.DecimalField(blank=True, db_column='CONDITION_MIN_VALUE', decimal_places=2, max_digits=10, null=True)),
                ('condition_max_value', models.DecimalField(blank=True, db_column='CONDITION_MAX_VALUE', decimal_places=2, max_digits=10, null=True)),
                ('comparison_variable', models.CharField(db_column='COMPARISON_VARIABLE', max_length=255)),
                ('comparison_min_value', models.DecimalField(blank=True, db_column='COMPARISON_MIN_VALUE', decimal_places=2, max_digits=10, null=True)),
                ('comparison_max_value', models.DecimalField(blank=True, db_column='COMPARISON_MAX_VALUE', decimal_places=2, max_digits=10, null=True)),
                ('comparison_operator', models.CharField(blank=True, db_column='COMPARISON_OPERATOR', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(db_column='SUB_CATEGORY_ID', on_delete=django.db.models.deletion.CASCADE, to='masters.mstsubcategory')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MstVerifierField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_column='FIELD_NAME', max_length=255)),
                ('category', models.ForeignKey(blank=True, db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.mstcategory')),
                ('component', models.ForeignKey(blank=True, db_column='COMPONENT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.mstcomponent')),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ManyToManyField(blank=True, db_column='SUB_CATEGORY_ID', null=True, to='masters.mstsubcategory')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MstVerifierRules',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('design_doc', models.CharField(db_column='DESIGN_DOC', max_length=255)),
                ('rule_number', models.CharField(db_column='RULE_NUMBER', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('verifier_field', models.ForeignKey(db_column='VERIFIER_FIELD_ID', on_delete=django.db.models.deletion.CASCADE, to='masters.mstverifierfield')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
