# Generated by Django 5.0.10 on 2025-01-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_mstcategory_is_verifier_mstsubcategory_is_verifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mstconditions',
            options={'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='mstverifierfield',
            options={'verbose_name': 'Verifier Field', 'verbose_name_plural': 'Verifier Fields'},
        ),
        migrations.AlterModelOptions(
            name='mstverifierrules',
            options={'verbose_name': 'Verifier Rule', 'verbose_name_plural': 'Verifier Rules'},
        ),
        migrations.AlterField(
            model_name='mstconditions',
            name='comparison_operator',
            field=models.CharField(blank=True, db_column='COMPARISON_OPERATOR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mstconditions',
            name='condition_operator',
            field=models.CharField(blank=True, db_column='CONDITION_OPERATOR', max_length=10, null=True),
        ),
    ]
