# Generated by Django 5.0.10 on 2025-01-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_mstconditions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstconditions',
            name='comparison_operator',
            field=models.CharField(blank=True, choices=[('gte', 'Greater than or equal to'), ('gt', 'Greater than'), ('eq', 'Equal to'), ('lt', 'Less than'), ('lte', 'Less than or equal to'), ('range', 'Within a range')], db_column='COMPARISON_OPERATOR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mstconditions',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('gte', 'Greater than or equal to'), ('gt', 'Greater than'), ('eq', 'Equal to'), ('lt', 'Less than'), ('lte', 'Less than or equal to'), ('range', 'Within a range')], db_column='CONDITION_OPERATOR', max_length=10, null=True),
        ),
    ]
