# Generated by Django 5.0.10 on 2025-01-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_mstconditions_comparison_operator_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mstsectiongroupings',
            unique_together={('design_doc', 'section_name')},
        ),
        migrations.AlterUniqueTogether(
            name='mstverifierfield',
            unique_together={('component', 'category', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='mstverifierrules',
            unique_together={('verifier_field', 'design_doc', 'rule_number')},
        ),
    ]
