# Generated by Django 5.0.10 on 2025-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_mstcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstsectionrules',
            name='rule_number',
            field=models.CharField(db_column='RULE_NUMBER', max_length=50),
        ),
    ]
