# Generated by Django 5.0.10 on 2025-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_mstsectionrules_rule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstsectionrules',
            name='parameter',
            field=models.CharField(db_column='PARAMETER', max_length=1255),
        ),
    ]
