# Generated by Django 5.0.10 on 2025-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_mstsectionrules_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstverifierrules',
            name='conditional_var',
            field=models.CharField(blank=True, db_column='CONDITIONAL_VAR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mstverifierrules',
            name='value',
            field=models.CharField(blank=True, db_column='VALUE', max_length=10, null=True),
        ),
    ]
