# Generated by Django 5.0.10 on 2025-03-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_mstverifierrules_conditional_var_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mstcategory',
            options={'verbose_name': '02 Category', 'verbose_name_plural': '02 Categories'},
        ),
        migrations.AlterModelOptions(
            name='mstcomponent',
            options={'verbose_name': '01 Component', 'verbose_name_plural': '01 Components'},
        ),
        migrations.AlterModelOptions(
            name='mstconditions',
            options={'verbose_name': '10 Condition', 'verbose_name_plural': '10 Conditions'},
        ),
        migrations.AlterModelOptions(
            name='mstdesignoptions',
            options={'verbose_name': '05 DesignOption', 'verbose_name_plural': '05 DesignOptions'},
        ),
        migrations.AlterModelOptions(
            name='mstsectiongroupings',
            options={'verbose_name': '07 Section Group', 'verbose_name_plural': '07 Section Groups'},
        ),
        migrations.AlterModelOptions(
            name='mstsectionrules',
            options={'verbose_name': '06 Section Rule', 'verbose_name_plural': '06 Section Rules'},
        ),
        migrations.AlterModelOptions(
            name='mstsubcategory',
            options={'verbose_name': '03 Sub Category', 'verbose_name_plural': '03 Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='mstsubcategorytwo',
            options={'verbose_name': '04 Sub Category Two', 'verbose_name_plural': '04 Sub Category Twos'},
        ),
        migrations.AlterModelOptions(
            name='mstverifierfield',
            options={'verbose_name': '08 Verifier Field', 'verbose_name_plural': '08 Verifier Fields'},
        ),
        migrations.AlterModelOptions(
            name='mstverifierrules',
            options={'verbose_name': '09 Verifier Rule', 'verbose_name_plural': '09 Verifier Rules'},
        ),
        migrations.AddField(
            model_name='mstconditions',
            name='category',
            field=models.ForeignKey(blank=True, db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.mstcategory'),
        ),
        migrations.AlterField(
            model_name='mstconditions',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='SUB_CATEGORY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.mstsubcategory'),
        ),
    ]
