# Generated by Django 5.0.10 on 2025-01-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0003_cadapprovertemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadapprovertemplates',
            name='comments',
            field=models.TextField(blank=True, db_column='APPROVER_COMMENTS', null=True),
        ),
        migrations.AddField(
            model_name='cadapprovertemplates',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_column='APPROVER_STATUS', max_length=8, null=True),
        ),
    ]
