# Generated by Django 5.0.10 on 2025-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0004_cadapprovertemplates_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='status',
            field=models.CharField(blank=True, db_column='APPROVER_STATUS', max_length=8, null=True),
        ),
    ]
