# Generated by Django 5.0.10 on 2025-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0005_alter_cadapprovertemplates_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='edu_number',
            field=models.CharField(db_column='EDU_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='model_name',
            field=models.CharField(db_column='MODEL_NAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='opp_number',
            field=models.CharField(db_column='OPP_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='opu_number',
            field=models.CharField(db_column='OPU_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='part_number',
            field=models.CharField(db_column='PART_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadapprovertemplates',
            name='revision_number',
            field=models.CharField(db_column='REVISION_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='caddesigntemplates',
            name='edu_number',
            field=models.CharField(db_column='EDU_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='caddesigntemplates',
            name='model_name',
            field=models.CharField(db_column='MODEL_NAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='caddesigntemplates',
            name='opp_number',
            field=models.CharField(db_column='OPP_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='caddesigntemplates',
            name='opu_number',
            field=models.CharField(db_column='OPU_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='caddesigntemplates',
            name='part_number',
            field=models.CharField(db_column='PART_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='caddesigntemplates',
            name='revision_number',
            field=models.CharField(db_column='REVISION_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadverifiertemplates',
            name='edu_number',
            field=models.CharField(db_column='EDU_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadverifiertemplates',
            name='model_name',
            field=models.CharField(db_column='MODEL_NAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadverifiertemplates',
            name='opp_number',
            field=models.CharField(db_column='OPP_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadverifiertemplates',
            name='opu_number',
            field=models.CharField(db_column='OPU_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadverifiertemplates',
            name='part_number',
            field=models.CharField(db_column='PART_NUMBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadverifiertemplates',
            name='revision_number',
            field=models.CharField(db_column='REVISION_NUMBER', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cadapprovertemplates',
            unique_together={('opp_number', 'opu_number', 'edu_number', 'model_name', 'part_number', 'revision_number')},
        ),
        migrations.AlterUniqueTogether(
            name='caddesigntemplates',
            unique_together={('opp_number', 'opu_number', 'edu_number', 'model_name', 'part_number', 'revision_number')},
        ),
        migrations.AlterUniqueTogether(
            name='cadverifiertemplates',
            unique_together={('opp_number', 'opu_number', 'edu_number', 'model_name', 'part_number', 'revision_number')},
        ),
    ]
