# Generated by Django 5.0.10 on 2025-02-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0006_alter_cadapprovertemplates_edu_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caddesigntemplates',
            name='secondary_sub_level',
            field=models.JSONField(blank=True, db_column='SECONDARY_SUB_LEVEL', null=True),
        ),
    ]
