# Generated by Django 5.0.10 on 2025-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0008_alter_cadapprovertemplates_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caddesigntemplates',
            name='remarks',
            field=models.TextField(blank=True, db_column='REMARKS', null=True),
        ),
    ]
