# Generated by Django 5.0.10 on 2025-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_to_draw', '0009_caddesigntemplates_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadverifiertemplates',
            name='remarks',
            field=models.TextField(blank=True, db_column='REMARKS', null=True),
        ),
    ]
